# This service definition provides the capabilities report for a NEPI SVX (servo) actuator
# One SVX device = one servo

---
string device_name
string device_path
string device_node_name

uint8 mode

bool has_absolute_positioning   # set by gotoPositionCb
bool has_adjustable_speed       # set by setSpeedRatioCb + getSpeedRatioCb
bool has_limit_control          # set by getSoftLimitsCb
bool has_homing                 # set by goHomeCb
bool has_set_home               # set by setHomePositionHereCb
bool has_spin_control           # if servo is continuous
bool has_goto_control
bool has_stop_control

float32 max_speed_dps
